---

s3:
  bucket: "ld-shared-prod-eu-west-2-ec2-inventory"
  key: "ec2_inventory-current.csv"

azure_ad:
  tenant_id: "a7bbe832-532a-4d60-930a-c47c8840745e"
  client_id: "a9a6fab8-df34-4589-8df5-0c68e7199ca5"
  redirect_url: "https://ec2-restart-manager.prod.ld.internal/auth/callback"
  group_id: "e0841785-e652-4a73-a748-f185a8a57a7a"

region: "eu-west-2"